### ISSUE TITLE
Version 1.4.0 on Confluent Hub

### ISSUE THREAD

**Issue by srolija** [hpgrahsl/kafka-connect-mongodb#120]
It seems that the latest version was only released to [Maven](https://mvnrepository.com/artifact/at.grahsl.kafka.connect/kafka-connect-mongodb) is there any reason it was not released on the [Confluent Hub](https://www.confluent.io/hub/hpgrahsl/kafka-connect-mongodb) as well?

Thanks for the great library!

**Comment by hpgrahsl** [comment]
Hi @srolija THX for reaching out and your kind words!

It's a bit unfortunate that so far version 1.4.0 was never published to the HUB. I'm already in touch with the folks from Confluent and it should be released at the HUB rather soon. Will keep you posted!

As always I'm happy to learn about your use case for the sink connector. So maybe you can share what you are doing with it in your projects. You can reach out also via email if you want.

**Comment by hpgrahsl** [comment]
and v1.4.0 is published to the HUB as well. so grab it from there anytime you need it :) 
https://www.confluent.io/hub/hpgrahsl/kafka-connect-mongodb

**Comment by srolija** [comment]
Great, thanks a lot! :) 

We are trying to get it running in combination with https://github.com/blueapron/kafka-connect-protobuf-converter to get quick and dirty solution for logging of proto messages for some debugging queries.
