### ISSUE TITLE
where is the jar?

### ISSUE THREAD

**Issue by kristofferth** [hpgrahsl/kafka-connect-mongodb#123]
i cant find it

**Comment by hpgrahsl** [comment]
you have 2 options:

1.  either get it via maven  https://search.maven.org/artifact/at.grahsl.kafka.connect/kafka-connect-mongodb/1.4.0/jar

2. or from confluent hub https://www.confluent.io/hub/hpgrahsl/kafka-connect-mongodb

also feel free to build it from sources if you don't like these options.
