### ISSUE TITLE
Parse Json data in PostProcessor

### ISSUE THREAD

**Issue by ngwwm** [hpgrahsl/kafka-connect-mongodb#16]
Dear Sir,
Thanks for the great product. We tried and be able to sink data to Mongodb successfully. Below is the data in Mongodb.
{
        "_id" : ObjectId("5a692f9742dc219e1e9ffcf5"),
        "gateway_id" : "XX:XX:XX:XX:XX:XX",
        "gateway_ip" : "10.0.0.1",
        "device_id" : "YY:YY:YY:YY:YY:YY",
        "device_type" : "bp",
        "jdata" : "{\"patientid\":\"1234\",\"systolic\":87,\"diastolic\":74,\"pulserate\":67}",
        "data_timestamp" : "2018-01-01 09:15:00"
}

You can see the "jdata" is in a string in json format. The source data is from third part and we can't change it. So, I would like to use the PostProcess capability of your connector to parse, convert and update it before writing to Mongodb.

I have studied the class DocumentIdAdder.java. But, not so sure how to proceed. e.g. I don't know how to use SinkDocument and SinkRecord.

Regards,
wwm

**Comment by ngwwm** [comment]
Sorry, jdata should be like this.
 "jdata" : "{\\"patientid\\":\\"1234\\",\\"systolic\\":150,\\"diastolic\\":52,\\"pulserate\\":96}",

**Comment by hpgrahsl** [comment]
Hi,Thanks for reaching out. It's good to hear that you enjoy working with my sink connector. The PostProcessor you would need should be pretty straight forward. All you need to do is take the value of the field (jdata) from the value doc, parse the contained string to a BsonDocument and replace the old String value with the result. If you need any help let me know :)Am 25.01.2018 6:41 Vorm. schrieb ngwwm <notifications@github.com>:Dear Sir,
Thanks for the great product. We tried and be able to sink data to Mongodb successfully. Below is the data in Mongodb.
{
"_id" : ObjectId("5a692f9742dc219e1e9ffcf5"),
"gateway_id" : "XX:XX:XX:XX:XX:XX",
"gateway_ip" : "10.0.0.1",
"device_id" : "YY:YY:YY:YY:YY:YY",
"device_type" : "bp",
"jdata" : "{"patientid":"1234","systolic":87,"diastolic":74,"pulserate":67}",
"data_timestamp" : "2018-01-01 09:15:00"
}
You can see the "jdata" is in a string in json format. The source data is from third part and we can't change it. So, I would like to use the PostProcess capability of your connector to parse, convert and update it before writing to Mongodb.
I have studied the class DocumentIdAdder.java. But, not so sure how to proceed. e.g. I don't know how to use SinkDocument and SinkRecord.
Regards,
wwm

**Comment by ngwwm** [comment]
Yes, I would need some help. I am not good in Java.

    @Override
    public void process(SinkDocument doc, SinkRecord orig) {    	    	
        doc.getValueDoc().ifPresent(vd -> {             
    			String jdata = vd.getString("jdata").getValue();
    			BsonDocument jdataDoc = vd.parse(jdata);
                        **--I am stuck here. don't know how to replace the old string.**
         	}
        );        
        getNext().ifPresent(pp -> pp.process(doc, orig));
    }

Regards,
wwm

**Comment by hpgrahsl** [comment]
@ngwwm ok. so you would need something like the following along the lines:

`@Override
public void process(SinkDocument doc, SinkRecord orig) {    	    	
    doc.getValueDoc().ifPresent(vd -> {             
                        //you should either check if jdata exists and/or provide a default value e.g. empty doc '{}' 
			String jdata = vd.getString("jdata").getValue();
			BsonDocument jdataDoc = BsonDocument.parse(jdata);
                        //by putting to the same fieldname you effectively override the old string value
                        vd.put("jdata",jdataDoc);
     	}
    );        
    getNext().ifPresent(pp -> pp.process(doc, orig));
}`

this should basically do it.

BTW I'm planning to include a JSON string post processor for a future release which is configurable and would convert also multiple or potentially nested fields as well. Thx for bringing this up.

**Comment by ngwwm** [comment]
Thanks a lot! With your kindly help, I achieved what I want.
Sure, you can close the issue.

**Comment by hpgrahsl** [comment]
You're welcome!
