### ISSUE TITLE
Is a connection with a MongoDB replica set possible?

### ISSUE THREAD

**Issue by qudoWru** [hpgrahsl/kafka-connect-mongodb#19]
Hi
I'm currently looking for a way to catch data from my kafka topics into my MongoDB replica set.

I've seen, you have defined the property "mongodb.connection.uri". 
Is it possible to provide here an uri string for an MongoDB replica set, like this:

`mongodb://[USER]:[PASSWORD]@host_1:27017,host_2:27017,host_3:27017/dbmane?replicaSet=replica-set-name`

**Comment by hpgrahsl** [comment]
hi @qudoWru 

thx for reaching out. what you find in the official docs about the connection uri format should work. so yes, it should definitely be possible to connect to a replica set or even a shard as well.

please give it a try in your environment and let me know.

**Comment by hpgrahsl** [comment]
@qudoWru do you already have feedback if connection to you replica set works as expected?
if so it would be nice of you to let me know and also close the issue. thx.

**Comment by qudoWru** [comment]
Hi @hpgrahsl hpgrahsl,

I'll test it today and post the results here.

**Comment by qudoWru** [comment]
Hi @hpgrahsl,

I'll test it today and post the results here.

**Comment by qudoWru** [comment]
Hi @hpgrahsl,

we used former an older version of connector and had some problems with connecting to replica set. 
After upgrade to the latest version it is working now.

Thanks!

**Comment by hpgrahsl** [comment]
It's good to hear that it works as expected :) THX for closing the issue!
