### ISSUE TITLE
MongoDBConnector not assigned any tasks

### ISSUE THREAD

**Issue by pederpansen** [hpgrahsl/kafka-connect-mongodb#2]
Hi,

I have the following problem: I have 4 different topics, each connected to the same MongoDB instance via a separate MongoDBConnector. 2 out of the 4 connectors are running fine and have one task each assigned. The other 2 connectors don't have any task assigned (visible via the REST API, `GET /connectors/{my_connector}/status`).

- Restarting the connector via `POST /connectors/{my_connector}/restart` does not help, after restart the connector still has no tasks
- Completely deleting and re-creating the connector does not help either

Is there per chance any stale data on the connect worker that needs to be cleaned? Looking at the logs of the Kafka Connect Docker Container is overwhelming, since the other 2 working connectors are producing a lot of output and I don't know what to `grep` for.

**Update**: If I delete the original connector and re-create it under a different name, it seems to work: The connector assigns one task and works normally.

Any idea how to go about?

**Comment by hpgrahsl** [comment]
hi!

first of all thx for using the connector and reporting your problem. it's actually really hard to tell without having information from the logs so I try my luck and make an educated guess :)

it might be the case that you are using 4 different instances all having the same **name property** set in their config. if you want them to work separately on topics try to specify different names and let me know if this helps.

to access the logs you can then grep for lines containing the respective connector instance's name e.g. like `cat connector.log | grep <your_name_here>` which should give you the lines relevant to the instance in question. this should help you track down the issue.

regards, hanspeter

**Comment by hpgrahsl** [comment]
@pederpansen did you make any progress based on my comment above? in case you succeeded to get it running I would suggest to close the issue...

**Comment by pederpansen** [comment]
Sorry for not coming back to you earlier.

All of my four connectors had different names and consumed different topics, so I don't think that was the issue.

When grepping the logs, I saw messages related to my unsuccessful attempts of restarting and deleting/re-creating the connectors, but no related errors or exceptions why the corresponding task did not start.

However, since at the moment the connectors (with new names) are running fine, I will close this issue for now and report back in case it should crash again.
