### ISSUE TITLE
BSON dependency missing in pom.xml

### ISSUE THREAD

**Issue by pederpansen** [hpgrahsl/kafka-connect-mongodb#20]
Hi HP,

I think your current master is missing the following dependency in `pom.xml`:

```
<dependency>
  <groupId>org.mongodb</groupId>
  <artifactId>bson</artifactId>
  <version>${mongodb.driver.version}</version>
</dependency>
```

Best,
Jurgis

**Comment by hpgrahsl** [comment]
hi @pederpansen 

actually I'd be surprised if that would be the case. tried to reproduce a missing dependency issue with the bson artifact you are referring to but couldn't.

local maven build works
local IDE build works
travis CI build works 

also when I manually look into the assembly jar after the successful build the BSON classes in question are contained. the bson.jar should be included as a transitive dependency by maven based on the mongo-driver artefact. 

can you please get back to me with more details in case you cannot build without explicitly listing the bson artefact in the pom file? it should work as is.

**Comment by pederpansen** [comment]
Indeed, I was not able to reproduce the build error on my private computer. I imagine my maven cache or my company's artifactory could have interfered.

**Comment by hpgrahsl** [comment]
Thx for you clarifying answer and closing the issue!

**Comment by pederpansen** [comment]
Pingback: I was not able to reproduce the issue. The .m2 cache moves in mysterious ways ;)
