### ISSUE TITLE
End2End Test failing because kafka-connect cannot see MongoDbSinkConnector plugin

### ISSUE THREAD

**Issue by adamarla** [hpgrahsl/kafka-connect-mongodb#28]
When attempting to execute the end2end test `MinimumViableIT`, `MongoDbSinkConnector` is not listed as an available connector in the list. Part of error HTTP response body is:
> "error_code":500,"message":"Failed to find any class that implements Connector and which name matches at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector, available connectors are: ...
goes on to list all of the other connectors (FileStreamSinkConnector, FileStreamSourceConnector.. etc.) that are available. 

Development machine is a Mac running OS X High Sierra with Docker Version 18.03.0-ce-mac60.

Added following to `/etc/hosts` 
`127.0.0.1	mongodb zookeeper kafkabroker schemaregistry kafkaconnect`

Some sort of a bootstrapping issue? Something simple that I am missing?

**Comment by adamarla** [comment]
Sorry, oversight on my part. The gradle build was dropping the jar files in a different libs/target directory and kafka-connector could not see them. I need to finalize gradle build script so that it can work seamlessly with the maven config and send it in so it can become part of the repo.

**Comment by hpgrahsl** [comment]
No problem. Thx for diving into this matter and working on a gradle build. I'm sure a bunch of people will appreciate that over my somewhat conservative maven approach ;-)
