### ISSUE TITLE
ReplaceOneBusinessKeyFilterStrategy (Avro-Schema) - compound keys do not seem to be working correctly

### ISSUE THREAD

**Issue by adamarla** [hpgrahsl/kafka-connect-mongodb#29]
I created a schema that looks something like this 
```
schema = {
    "type": "record",
    "name": "TestPricingData",
    "namespace": "com.runtitle.data.kafka.avro",
    "doc": "Test Pricing Record",
    "fields": [
        {"name": "source_system_id", "type": "string"},
	{"name": "source_record_id", "type": "string"},
        {"name": "indexes", "type": { "type": "array", "items": "string"}},
        {"name": "raw_acres", "type": "int"}
    ]
}
```
the first two fields `source_system_id` and `source_record_id` together form a BusinessKey. My mongo sink config looks like this
```
config = {
  "name": "mongo-sink-pricing-data",
  "config": {
    "topics": "pricing-data",
    "connector.class": "at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector",
    "key.converter": "io.confluent.connect.avro.AvroConverter",
    "key.converter.schema.registry.url": "http://kafka.schema:8081",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url": "http://kafka.schema:8081",
    "mongodb.connection.uri": "mongodb://docker.for.mac.localhost:27017/titletime?w=1&journal=true",
    "mongodb.document.id.strategy": "at.grahsl.kafka.connect.mongodb.processor.id.strategy.PartialValueStrategy",
    "mongodb.key.projection.list": "source_system_id, source_record_id",
    "mongodb.key.projection.type": "whitelist",
    "mongodb.collection": "pricingData",
    "mongodb.replace.one.strategy": "at.grahsl.kafka.connect.mongodb.writemodel.filter.strategy.ReplaceOneBusinessKeyFilterStrategy"
  }
}
```
However if I send two successive messages where I keep the same `source_system_id` and change the `source_record_id`, instead of creating a new record it updates the existing record. For e.g.
Message 1 - `{source_system_id: "SYS1", source_record_id: "REC1"}`
results in DB record 
`{_id: ObjectId("5ac704819b0241d8b69ad276"), source_system_id: "SYS1", source_record_id: "REC1"}`
However if now i send
Message 2 - `{source_system_id: "SYS1", source_record_id: "REC2"}`
Instead of creating a new record, it updates the same record to
`{_id: ObjectId("5ac704819b0241d8b69ad276"), source_system_id: "SYS1", source_record_id: "REC2"}`

Recording the issue here, I will be looking into this at my end as well.

**Comment by hpgrahsl** [comment]
Thx @adamarla for reporting this. I'll look into it to see what could be wrong.

**Comment by hpgrahsl** [comment]
@adamarla I just tried your example and found what is wrong. A minor issue which should definitely be addressed with a fix but nothing to really worry about :) The problem you are facing is related to whitespaces for the field projection settings. There is a space before the second field in the key list which is not trimmed. In fact all K/V projections are affected by this so in the meantime please make sure not to have whitespaces in the config when defining the lists. For me writing the config like this works:

`{"mongodb.key.projection.list": "source_system_id,source_record_id"}`

Can you please verify it on your side and report back if it works?

**Comment by adamarla** [comment]
Looks good. The behavior looks in accordance with the explanation.
