### ISSUE TITLE
License

### ISSUE THREAD

**Issue by marcusadair** [hpgrahsl/kafka-connect-mongodb#3]
Thanks for the work on this nice little driver. 

Would you mind to clarify the license you're releasing under? Sorry if it's already mentioned and I missed it.

**Comment by hpgrahsl** [comment]
Hi! First of all thx for your interest in this project.No you didn't miss it ;) I forgot to put specific license information into the sources and readme. Will be able to hopefully do that by tomorrow...Which one is going to be related to other connectors and Kafka itself. I'll let you know.RegardsOn 25 Apr 2017 4:42 p.m., marcusadair <notifications@github.com> wrote:Thanks for the work on this nice little driver.
Would you mind to clarify the license you're releasing under? Sorry if it's already mentioned and I missed it.

**Comment by hpgrahsl** [comment]
Done! all sources now include the license information header... Apache V2 it is :) 
https://www.apache.org/licenses/LICENSE-2.0

**Comment by marcusadair** [comment]
Thanks!
