### ISSUE TITLE
JsonParseException with a string key

### ISSUE THREAD

**Issue by invadergir** [hpgrahsl/kafka-connect-mongodb#36]
Hi, 

I am trying to sink to mongodb from a kafka topic that has a string key (simple text) and raw JSON as the message, and I get an exception when I post my connector config to kafka-connect.  (I have data in the topic already so the connector processing starts as soon as I post to kafka-connect.)  Any advice would be appreciated.  Note that I'm not running with confluent platform, just straight kafka.  In this example, the keys for all my kafka messages are "SZ0".  

The library version tested is v1.0.0.

Exception:
```
[2018-05-04 13:58:39,898] ERROR WorkerSinkTask{id=bare-mongodbsink.json-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:515)
org.bson.json.JsonParseException: JSON reader was expecting a value but found 'SZ0'.
        at org.bson.json.JsonReader.readBsonType(JsonReader.java:251)
        at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:682)
        at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:724)
        at org.bson.AbstractBsonReader.readStartDocument(AbstractBsonReader.java:452)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:81)
        at org.bson.BsonDocument.parse(BsonDocument.java:62)
        at at.grahsl.kafka.connect.mongodb.converter.JsonRawStringRecordConverter.convert(JsonRawStringRecordConverter.java:34)
        at at.grahsl.kafka.connect.mongodb.converter.SinkConverter.convert(SinkConverter.java:44)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$buildWriteModel$1(MongoDbSinkTask.java:148)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.buildWriteModel(MongoDbSinkTask.java:147)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.put(MongoDbSinkTask.java:107)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2018-05-04 13:58:39,901] ERROR WorkerSinkTask{id=bare-mongodbsink.json-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:517)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.bson.json.JsonParseException: JSON reader was expecting a value but found 'SZ0'.
        at org.bson.json.JsonReader.readBsonType(JsonReader.java:251)
        at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:682)
        at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:724)
        at org.bson.AbstractBsonReader.readStartDocument(AbstractBsonReader.java:452)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:81)
        at org.bson.BsonDocument.parse(BsonDocument.java:62)
        at at.grahsl.kafka.connect.mongodb.converter.JsonRawStringRecordConverter.convert(JsonRawStringRecordConverter.java:34)
        at at.grahsl.kafka.connect.mongodb.converter.SinkConverter.convert(SinkConverter.java:44)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$buildWriteModel$1(MongoDbSinkTask.java:148)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.buildWriteModel(MongoDbSinkTask.java:147)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.put(MongoDbSinkTask.java:107)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
        ... 10 more
[2018-05-04 13:58:39,901] ERROR WorkerSinkTask{id=bare-mongodbsink.json-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:173)
[2018-05-04 13:58:39,902] INFO stopping MongoDB sink task (at.grahsl.kafka.connect.mongodb.MongoDbSinkTask:182)                       
```

Here is the config I used:

```
{
    "name": "bare-mongodbsink.json",
    "config": {
        "connector.class": "at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector",
          
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "key.converter.schemas.enable": false,
          
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": false,
          
        "topics": "sensed-metrics",

        "mongodb.document.id.strategy": "at.grahsl.kafka.connect.mongodb.processor.id.strategy.BsonOidStrategy",
        
        "mongodb.connection.uri": "mongodb://localhost:27017/testdb?w=1&journal=true",
        "mongodb.collection": "sensedMetricsTest"
    }
}
```

And here is the kafka connect properties file:

```
bootstrap.servers=localhost:9092

group.id=connect-cluster

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter

key.converter.schemas.enable=false
value.converter.schemas.enable=false

internal.key.converter=org.apache.kafka.connect.storage.StringConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

offset.storage.topic=connect-offsets
offset.storage.replication.factor=1

config.storage.topic=connect-configs
config.storage.replication.factor=1

status.storage.topic=connect-status
status.storage.replication.factor=1

offset.flush.interval.ms=10000



plugin.path=/opt/kafka-connectors
```

Thanks

**Comment by adamarla** [comment]
I suspect it might be that as you said the `keys` for your kafka messages are a string "SZ0" whereas as per the configuration `"key.converter": "org.apache.kafka.connect.json.JsonConverter"` a json payload is expected. If your key values are all the same, why don't you try leaving the key out altogether. It is not mandatory to pass a key.

**Comment by hpgrahsl** [comment]
hi @invadergir and thanks for getting in touch!

it would help if you can provide a concrete example for your key and value structure that is present in the topic in question. I can then try to take a look at it and get back to you how to proceed.

as @adamarla already mentioned if your key isn't JSON encoded but only raw strings it simply won't work when using the JsonConverter as key.converter in your config.

irrespective of this, I'm wondering why you are making use of the CDC feature. Is your data in the topic really coming from debezium source connector and originating from MongoDB? if not then this configuration option won't make sense.

**Comment by invadergir** [comment]
Hi, and thanks for responding.  I realized I posted the wrong config, so I retested with my configs and updated the results in the original post above.  All the configs above are exactly what I ran.  I made sure all the key converters were set to StringConverter, even the internal.key.converter; although I tested with and without the internal one set to StringConverter and it made no difference.  I made sure to remove the CDC stuff as well.

As requested here, is some example data in the topic I am trying to sink into mongo.  It's not exactly the data because it's sensitive but the keys, field types and number of fields are the same:

```
kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic sensed-metrics --from-beginning --formatter kafka.tools.DefaultMessageFormatter --property print.key=true --property print.value=true --property key.deserializer=org.apache.kafka.common.serialization.StringDeserializer --property value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
SZ0     {"time":"2018-05-04T13:58:39.475","inSync":"True","measurement":8.5344,"version":"1.0","address":"SI:M0:00:00:00:00","config":"/a/b/c/d.properties","type":"measurement"}
SZ0     {"time":"2018-05-04T13:58:39.854","inSync":"True","measurement":8.498724160550678,"version":"1.0","address":"SI:M0:00:00:00:00","config":"/a/b/c/d.properties","type":"measurement"}
SZ0     {"time":"2018-05-04T13:58:40.095","inSync":"True","measurement":8.463048321101356,"version":"1.0","address":"SI:M0:00:00:00:00","config":"/a/b/c/d.properties","type":"measurement"}
SZ0     {"time":"2018-05-04T13:58:40.841","inSync":"True","measurement":8.427372481652034,"version":"1.0","address":"SI:M0:00:00:00:00","config":"/a/b/c/d.properties","type":"measurement"}
```

**Comment by invadergir** [comment]
And regarding the keys being the same, eventually the kafka keys will all be different but for now I'm testing with one particular key.  I'd like to eventually store the _id fields in mongo as the kafka key plus "time" field, but for now I'd be happy to get the OID version working.

**Comment by hpgrahsl** [comment]
Sorry for getting back to this much later than expected. I had a bunch of other things to do lately. So the answer for now might also be not really satisfying for you. It's currently not possible since in case  the key and value are present for records we expect both of them to be structured data. this means it can be a plain string but it must be at least a valid json encoded string which in your example isn't the case. The reason for this is that we are dealing with a MongoDB documents that should get processed and finally saved. I'm thinking about if it makes to allow such scenarios at least for the key of records in future versions.

**Comment by hpgrahsl** [comment]
@invadergir would be interesting to know how you proceeded with this one? after thinking about it one more time in a bit more detail it's probably not the best idea to implement a connector specific feature which would allow for your use case. mostly because I think the easiest way to achieve what you need would be to make use of a simple [SMT (single message transform)](https://kafka.apache.org/documentation/#connect_transforms)* operation and just add it to the connector configuration. what the SMT would need to perform in your case is just wrapping the plain string key e.g. "SZ0" into a valid JSON string so that it becomes something like {"key":"SZ0"}. based on that you can run the mongodb-sink-connector which then has a valid key document to work with. let me know what you think or if you need any further help.

*in addition to the kafka docs you can also [find similar information in confluent docs](https://docs.confluent.io/current/connect/transforms/index.html)

**Comment by hpgrahsl** [comment]
@invadergir any news on this one? otherwise I'd like to close this for now if that's ok with you.

**Comment by jzuijlek** [comment]
I'm having the same issue with a slightly different use case. I'm using KSQL to aggregate a Kafka Stream. The resulting KSQL TABLE has string as key as well.

**Comment by hpgrahsl** [comment]
@jzuijlek I see. What about the SMT-based solution I'm suggesting above? A part from that since you are doing it based on KSQL what should also work is that you just wrap your flat string key e.g. `'abc123'` into a valid json string key `{'_id':'abc123'}` which should be straight forward by applying `CONCAT`. What do you think?

**Comment by jzuijlek** [comment]
I'm trying to use the SMT solution to generate an `_id` field I can use to upsert the records from the table.

**Comment by jzuijlek** [comment]
I got it working using SMT:

```
transforms=createKey
transforms.createKey.type=org.apache.kafka.connect.transforms.ValueToKey
transforms.createKey.fields=EVENT,SOURCEID

mongodb.document.id.strategy=at.grahsl.kafka.connect.mongodb.processor.id.strategy.PartialValueStrategy
mongodb.key.projection.type=whitelist
mongodb.key.projection.list=EVENT,SOURCEID
mongodb.replace.one.strategy=at.grahsl.kafka.connect.mongodb.writemodel.filter.strategy.ReplaceOneBusinessKeyFilterStrategy

```

**Comment by jzuijlek** [comment]
Yes, that also works, but I want an objectId as _id. Are there any negatives in using it this way?

**Comment by hpgrahsl** [comment]
@jzuijlek the way you are using it is fine. in fact it got introduced as an alternative behaviour due to a user request. if you need the objectid field created during first upsert operation than this is currently the way to go.

BTW would you be willing to share your use case of the sink connector (cf. the 2 testimonials at the beginning of the README? that would be very much appreciated. just let me know and I'm happy to feature it :)

**Comment by stephenBSL** [comment]
I am running into the same problem as original poster, but it's unclear to me how to use any of the SMTs listed on confluent to modify a key from string to json.  Any hints to achieve this?  I get the point of your suggestions but am not seeing an SMT that allows me to convert KEY to {"_id":"KEY"}.

**Comment by adrien-ben** [comment]
I, We also use this connector and ran into the same problem. We use Kafka connect transformation to wrap the key and do it like this:

 ```properties
transforms=WrapKey
transforms.WrapKey.type=org.apache.kafka.connect.transforms.HoistField$Key
transforms.WrapKey.field=_id
 ```

Confluent documentation on transformation is light but you can find more details in Apache Kafka documentation : https://kafka.apache.org/documentation/#connect

**Comment by stephenBSL** [comment]
Thank you @adrien-ben.

That does prevent the exception, however I am not seeing the key show up in the mongo document.
HoistField$Key seems to be having the same effect as Drop$Key, which I might be ok with.

**Comment by adrien-ben** [comment]
Yep I forgot something. You also have to set 

```properties
mongodb.document.id.strategy=at.grahsl.kafka.connect.mongodb.processor.id.strategy.ProvidedInKeyStrategy
```

So it actually uses the _id from the created key document

**Comment by stephenBSL** [comment]
Yes.  Thank you, adding that works.

**Comment by hpgrahsl** [comment]
@adrien-ben thx for your efforts and helping out here. @stephenBSL I'm glad to hear you found a solution. With regard to the DocumentIdStrategy do you think something is missing or not clear enough in the docs/README? I wrote it so I'm biased of course :)

**Comment by stephenBSL** [comment]
No, it's fine.  I went through so may iterations trying to figure out an SMT solution, that I overlooked the document id strategy once I had the SMTs settled.

**Comment by sourjya123** [comment]
Hi I have configured kafka mongo sink connector. I am publishing data with key. key =DEVICE_PROFILE and the data is json.

When I am running it showing below error
org.bson.json.JsonParseException: JSON reader was expecting a value but found 'DEVICE_PROFILE'.

In MongoDbSinkConnector.properties I have mentioned below lines.  
key.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false

value.converter=org.apache.kafka.connect.storage.StringConverter
value.converter.schemas.enable=false

Can you please check and let me know where I am going wrong.

**Comment by hpgrahsl** [comment]
@sourjya123 sorry but in case you run into the JsonParseException it's hard to believe that your key is represented by a valid JSON string. otherwise it would work. please carefully read everything above and verify your key. e.g. use the kafka-console-consumer and configure it to also print the key so that you see what it really contains for the topic you want to get processed by the sink connector.

**Comment by sourjya123** [comment]
Hi,

Ok the scenario is I am publishing data from mqtt to the topic mcd/
10.120.134.155/DEVICE_MESSAGES

once the message is published to mqtt I can able to get the data from Kafka
using Kafka consumer. I also printed the key it is the same as mqtt topic.

Now when the data reaches to sink connector it tries to deserialize the
key. Since the key is
mcd/10.120.134.155/DEVICE_MESSAGES
It can't deserialize the key by json converter. So can you please tell me
what should I do for this scenario to get passed.

**Comment by sourjya123** [comment]
DEBUG a.g.k.c.m.converter.SinkConverter - SinkRecord{kafkaOffset=0, timestampType=CreateTime} ConnectRecord{topic='DEVICE_PROFILE', kafkaPartition=0, key=mcd/10.120.12.134/DEVICE_PROFILE, keySchema=Schema{STRING}, value={status=off}, valueSchema=null, timestamp=1563392952346, headers=ConnectHeaders(headers=[ConnectHeader(key=kafka.mqtt.dup, value=false, schema=Schema{BOOLEAN}), ConnectHeader(key=kafka.mqtt.qos.level, value=2, schema=Schema{INT8}), ConnectHeader(key=kafka.mqtt.retain, value=false, schema=Schema{BOOLEAN}), ConnectHeader(key=kafka.mqtt.packet.id, value=1, schema=Schema{INT8})])}
20:03:05.834 [pool-2-thread-1] DEBUG a.g.k.c.m.converter.SinkConverter - using raw converter
20:03:05.837 [pool-2-thread-1] ERROR o.a.k.connect.runtime.WorkerSinkTask - WorkerSinkTask{id=MyMongoDbSinkConnector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted.
org.bson.json.JsonParseException: JSON reader was expecting a value but found 'mcd'.
        at org.bson.json.JsonReader.readBsonType(JsonReader.java:251)
        at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:680)
        at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:722)
        at org.bson.AbstractBsonReader.readStartDocument(AbstractBsonReader.java:450)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:81)
        at org.bson.BsonDocument.parse(BsonDocument.java:62)


This is the error I am getting while I am trying to store in Mongo

**Comment by sourjya123** [comment]
Do I need to use SMT for this? I have installed confluent-hub install confluentinc/connect-transforms:latest this. It has extract-topic.properties file.

Now how to use this file and where to use it. Can you please let me know or is there any way to do the conversion before sending to mongo.

**Comment by sourjya123** [comment]
> @invadergir would be interesting to know how you proceeded with this one? after thinking about it one more time in a bit more detail it's probably not the best idea to implement a connector specific feature which would allow for your use case. mostly because I think the easiest way to achieve what you need would be to make use of a simple [SMT (single message transform)](https://kafka.apache.org/documentation/#connect_transforms)* operation and just add it to the connector configuration. what the SMT would need to perform in your case is just wrapping the plain string key e.g. "SZ0" into a valid JSON string so that it becomes something like {"_id":"SZ0"}. based on that you can run the mongodb-sink-connector which then has a valid key document to work with. let me know what you think or if you need any further help.
> 
> *in addition to the kafka docs you can also [find similar information in confluent docs](https://docs.confluent.io/current/connect/transforms/index.html)

Where to configure this.

**Comment by adrien-ben** [comment]
In your connector's configuration. There's an example in this thread.

**Comment by yogi12121993** [comment]
hi, @hpgrahsl 
When I am publishing data to a particular topic in mosquito, at mongo sink connector I am getting that topic as key of kafka record using SMT(transforms=WrapKey). How can I extract that key(topic name) and store that into mongo along with value?

 ConnectRecord{topic='DEVICE_PROFILE', kafkaPartition=0, key=Struct{mqtt_topic=mcd/122.11.11.11/DEVICE_PROFILE}, keySchema=Schema{STRUCT}, value={"value1":2234,"value2":4564364332234},

![Screenshot (2)](https://user-images.githubusercontent.com/48271567/61458107-6c0d4980-a987-11e9-9cf2-80e464a821ac.png)

**Comment by Susheer** [comment]
> @jzuijlek glad to hear you got it working for your use case. just wondering if it would also work with the `ReplaceOneDefaultFilterStrategy` because it also support compound keys. The custom `ReplaceOneBusinessKeyFilterStrategy` is for very specific usage, namely if you absolutely need a MongoDB ObjectId to be created and at the same time need to have upsert semantics based on your business key.

 this worked for me. Thanks
