### ISSUE TITLE
Support for collection.name={$topic}

### ISSUE THREAD

**Issue by SkiaBr23** [hpgrahsl/kafka-connect-mongodb#45]
Hello!

I used another Kafka-Mongo sink connector a few months ago, and it has the feature to set the collection name to sink as "{$topic}", and i could listen to several topics and sink them to multiple collections.

If i'm not wrong, this connector do not have that feature. Is this doable? Would be a great help in my projects.

**Comment by hpgrahsl** [comment]
Hello Rafael!

First of all, I'm glad to hear that you are trying to run my connector :) Concerning your comment, you are right that the current implementation does not offer the feature you are mentioning. 

Nevertheless, I would like to learn more about your use case and the "project(s)" you are referring to.

As a side node, a very naive form of this feature could be easily added but in general it would not help a lot of users that I discussed this with already in the past. If you need this urgently I guess your best bet is to fork the repo and do a quick & dirty hack yourself.

Also may I ask which other sink you were using. It would also be interesting to know why you looked for something else, like my connector, and moved away from the other one.

**Comment by SkiaBr23** [comment]
@hpgrahsl Thanks for the quick reply!

I've been working with some sensors to measure energy consumption in my IoT startup and i found myself in need of a connector since i'm using MongoDB to store the data & Kafka as the main broker. I'm sending different types of data from the sensors to different topics in Kafka, and wanted them to end up in specific collections in the database. I started off using [this](https://github.com/RADAR-base/MongoDb-Sink-Connector) connector, that had the feature i mentioned. I had some problems with data conversion and serialization and found out about your implementation, that solved those problems and gave me way better customization options (congratulations by the way!).

I really want to keep using the connector and this feature is a must-have to my architecture. I can play a little by forking the repo and trying to code it myself for now =)

**Comment by hpgrahsl** [comment]
@SkiaBr23 thx for clarifying your use case by providing some more details.

The feature you suggest is in fact a bit more involved than it looks at first sight. I already discussed something similar with other users in the recent past. Find a quick summary of my thoughts below: 

1) Some general connect specific settings can only be defined once for an instance e.g. number of tasks, key and value converters, using the schema registry or not => so from what I've seen you cannot configure this on a topic level, yet different topics might need different settings for these as well and you would then have to run multiple connect instances anyway.

2) Coming back to my mongo sink and its specific settings: from my own experience (and also based on feedback from other users) only a handful of them (if at all) would be similar across different topics. This means that we would need to allow a large majority of the config settings to be defined individually for each and every topic, e.g. topics might need different id generation strategies, they would highly likely need completely different post processing chains etc.

Of course such behaviour can be implemented and it shouldn't be too hard but IMHO allowing this would lead to a long, complex and bloated single configuration file for typical real world scenarios. Other than that, it would also mean that if the connector fails with some unrecoverable exception for a specific topic it might not be able to happily continue its work for the other topics, which are potentially unaffected by the exception in question.

Although I'm aware that you might save some CPU/RAM resources by running fewer instances, I don't see any real issues with running multiple connect instances, effectively one for each topic... if it weren't for hundreds or thousands of topics of course ;-) 

What do you think?

**Comment by SkiaBr23** [comment]
@hpgrahsl thanks for the detailed answer and tips! I ended up using multiple instances of the connector for now and it's been a good fit for the project.

**Comment by hpgrahsl** [comment]
@SkiaBr23 great to hear that what I suggested is helpful and works for your current use case!

further I wanted to ask if you maybe would like to share your concrete use case so that I could feature it under [users / customer testimonials](https://github.com/hpgrahsl/kafka-connect-mongodb#users--testimonials) like the other two which are already present in the README. just let me know, would be highly appreciated to have an IoT related use case :)

**Comment by durduliu2009** [comment]
Hello @hpgrahsl I can give you a use case if I may.
For example I have 10 devices (or more doesn't matter) and those devices send data to kafka somehow it doesn't matter but i have for example 5 different types of values (1. batteryVoltage, 2. tankFuelLevel, 3. energyConsumed, 4. solarLoad, 5. windProduced energy) each parameter I want to store in a different collection/table (database) for each parameter from those 5 cases I will create a topic so will be 5 topics on broker. And this feature will help to automapping 5 topics to 5 collections/tables.
In that case I wont need to create 5 instances for each collection/table. Report will be 1:1 (topic to collection) on one single instance.

I hope you understand better why we need ${topic) feature. I'm waiting for your feedback
