### ISSUE TITLE
Key Renaming and skip null values are not Working 

### ISSUE THREAD

**Issue by durduliu2009** [hpgrahsl/kafka-connect-mongodb#47]
Hello,

Something is not ok when I make according changes with MongoDbSink because 
1. Json Keys are not renamed
2. Deny insert into mongo json with null values is not working even if is set to true

Bellow you find attached my conf.properties

name=MyMongoDbSinkConnector
topics=test,testkafka
tasks.max=1
#key.converter=io.confluent.connect.avro.AvroConverter
#key.converter.schema.registry.url=http://localhost:8081
#value.converter=io.confluent.connect.avro.AvroConverter
#value.converter.schema.registry.url=http://localhost:8081
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=true
connector.class=at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector
#specific MongoDB sink connector props
#listed below are the defaults
mongodb.connection.uri=mongodb://localhost:27017/kafka?w=1&journal=true
mongodb.collection=kafkatopic
mongodb.max.num.retries=3
mongodb.retries.defer.timeout=5000
mongodb.value.projection.type=none
mongodb.value.projection.list=
mongodb.document.id.strategy=at.grahsl.kafka.connect.mongodb.processor.id.strategy.BsonOidStrategy
mongodb.document.id.strategies=
mongodb.key.projection.type=none
mongodb.key.projection.list=
mongodb.field.renamer.mapping=[{"oldName":"key.myta","newName":"key.batteryVoltage"}]
mongodb.field.renamer.regexp=[]
mongodb.post.processor.chain=at.grahsl.kafka.connect.mongodb.processor.field.renaming.RenameByM$
#mongodb.field.renamer.regexp=[{"regexp":"^key\\..*my.*$","pattern":"my","replace":""},{"regexp$
mongodb.change.data.capture.handler=
mongodb.delete.on.null.values=true
mongodb.replace.one.strategy=at.grahsl.kafka.connect.mongodb.writemodel.filter.strategy.ReplaceOneDefaultFilterStrategy

Also I tried with 
`mongodb.field.renamer.mapping=[{"oldName":"myta","newName":"batteryVoltage"}]` but still nothing the json data is same.

What I send to topic is 
`{"schema":{"type":"struct","fields":[{"type":"string","optional":true,"field":"myta"}]},"payload":{"myta": "myta"}`

Please can someone help me on that matter ? 
I must tell that except that part were json data is not postprocessed by the connector,  data that is fetched from those 2 topics is inserted in collection succesfully

Also I have a question regarding method of how this connector insert data to MongoDb.
For each message that appears in broker topic this connector creates a insert cmd ? or data received in topic si stored in a buffer for 10 seconds for example and then this buffer is pushed to database with a bulk write operation ? 

If bulk write is available is there a chance to change parameter ? batch size, time untill batch expires and then bulk write data to database ? 

Thank you in advance,

**Comment by hpgrahsl** [comment]
Hi @durduliu2009 

Thanks for reaching out. I quickly looked into this

**Comment by hpgrahsl** [comment]
Hi @durduliu2009 

Thanks for reaching out. I'll quickly look into this later today. From what I've seen so far and if I understood you correctly it's some misconfiguration that most likely causes you trouble. Field renaming definitely works. Will check and get back to you.

**Comment by durduliu2009** [comment]
Also please if you are kind to respond my question 

> Also I have a question regarding method of how this connector insert data to MongoDb.
For each message that appears in broker topic this connector creates a insert cmd ? or data received in topic si stored in a buffer for 10 seconds for example and then this buffer is pushed to database with a bulk write operation ?

If bulk write is available is there a chance to change parameter ? batch size, time untill batch expires and then bulk write data to database ?

**Comment by hpgrahsl** [comment]
Hi again,

So with regard to your:

1. problem = renaming of fields

As I said the renaming works fine. What's important is that you configure the renaming settings properly and also take care that you do it for the key and/or value structure of the kafka sink record. To take your example you could e.g. use the following configuration settings:

Make sure to put the correct renamer in the post processor chain settings like so:

`mongodb.post.processor.chain=at.grahsl.kafka.connect.mongodb.processor.field.renaming.RenameByMapping`

Also define the renaming itself

`mongodb.field.renamer.mapping=[{"oldName":"key.myta","newName":"batteryVoltage"}]`

This will then cause a field named _myta_ in the **key(!) struct of the record** to be renamed to _batteryVoltage_. if the field is in the value struct then go with 'value.myta' instead.

2. problem = using the **mongodb.delete.on.null.values=true**

Maybe you misunderstood what this setting is supposed to do. The idea is that the sink connector will try to delete a mongodb document from the collection iff the whole value struct is null. Deletion will be done based on the _id field. But in your case you are using the BsonOidStrategy which will always create a new _id for each sink record which effectively means it will never delete anything, since you get a unique _id for every sink record which is processed. This setting can only be reasonably applied when you have an _id field based on a different DocumentIdStrategy. Hope this is clearer now.

**Comment by hpgrahsl** [comment]
And finally about your comment about error handling. Short answer NO(!) you cannot simply ignore such severe issues which result from a parse error of the whole message - this would also make no sense. Also such errors affect the connect framework code meaning they happen before the specific sink connector code kicks in. You have several options to configure how the key and value struct are encoded. In your config example above your are doing the following:

_key.converter=org.apache.kafka.connect.json.JsonConverter_
**key.converter.schemas.enable=false**

This means the **key is encoded as JSON string but without(!) explicit schema information**.

value.converter=org.apache.kafka.connect.json.JsonConverter
**value.converter.schemas.enable=true**

This means the **value is encoded as JSON string but with(!) explicit schema information**.

Thus, whenever a kafka record in the corresponding topic would violate this configuration the connector cannot parse and handle the record correctly. You should absolutely make sure that you don't let producers send "garbage data" (i.e. invalid records) to your topics :)

**Comment by durduliu2009** [comment]
Ok i will try as you said and then i will come back with a feedback. Please let this topic open for few days. Thank you

**Comment by durduliu2009** [comment]
As I promised I'm coming back with confirmation for key/value renaming. Yes it is functional :) 
Also many thanks for your advice(s). Sorry if I'm asking again but I saw in your documentiation that `The sink records are converted to BSON documents which are in turn inserted into the corresponding MongoDB target collection. The implementation uses unorderd bulk writes.`. OK this responds to one of my questions if this connector uses bulk writes as main write to MongoDb **BUT** how it does it ? (in which interval ms or batch size ? Can I change somehow those settings if exists (batch ms or batch size) ? 

Thank you again for your support.

**Comment by durduliu2009** [comment]
Good. Many thanks for these usefull informations. I'm curios regarding #45 (https://github.com/hpgrahsl/kafka-connect-mongodb/issues/45) if  you plan to develop this kind of feature. Also I tried to give you a good exemple of why and how we can use this kind of feature. Thank you again.
