### ISSUE TITLE
[feature request] support multiple topics

### ISSUE THREAD

**Issue by hpgrahsl** [hpgrahsl/kafka-connect-mongodb#52]
One of the most requested features based on user feedback so far is to have support for storing kafka records from different topics into separate mongodb collections. see e.g. [#45,#48]

there are basically two ways to achieve that:

1. the naive way is to simply write every record to a collection in mongodb with the same name that's specified as record name in the sink record. problem is that it would most likely not work since we have to expect different kafka topics to contain completely different data and therefore a lot of configuration settings might be different as well.

2. a bit more complex: enable a more flexible / sophisticated way to define all relevant configuration options on a topic level so that users can fully benefit of this feature. ideally there is an overriding mechanism in place which allows to change settings specifically on a topic-basis. at the same time this means that there should be fallback settings when nothing is defined at the topic-level.

implementing the 2nd option should be the best way to go :)

**Comment by hpgrahsl** [comment]
FYI @durduliu2009 @SkiaBr23 since you asked for this a while ago -> eventually a first version of this feature is already in development :)

**Comment by durduliu2009** [comment]
@hpgrahsl those are great news !!! I look forward for this to have some tests with this new feature !!!

**Comment by hpgrahsl** [comment]
FYI @durduliu2009 @SkiaBr23 it's available as of now. Documentation see https://github.com/hpgrahsl/kafka-connect-mongodb#collection-aware-configuration-settings

**Comment by SkiaBr23** [comment]
@hpgrahsl Just saw this. Great work on the feature, actually way more helpful than i expected. Kudos!
