### ISSUE TITLE
Schema registry URL setting from control center is missing.

### ISSUE THREAD

**Issue by Manish-Sharma2015** [hpgrahsl/kafka-connect-mongodb#57]
Hello Team,

I tried configuring the mongoDB sink connector through Confluent Control Center. I could not see "value.converter.schema.registry.url" property to set the schema registry URL. I had to use the connect REST API to update this property at sink connector instance level.

Not sure if this is an issue or expected behavior. Please help.

**Comment by hpgrahsl** [comment]
@Manish-Sharma2015 could you maybe provide the information I was asking for? otherwise I'd suggest it makes sense to close this issue after > 2 weeks without a comment from your side.

**Comment by Manish-Sharma2015** [comment]
Thanks for the response. Let me check with confluent providing this property in control center.
