### ISSUE TITLE
[feature request] publish sink connector artifact to maven central

### ISSUE THREAD

**Issue by zthulj** [hpgrahsl/kafka-connect-mongodb#74]
Hey,

In order to be able to create a projet with one or more postProcessor, I think that It would be a good idea to publish the current connector project to the central nexus.

**Comment by hpgrahsl** [comment]
@zthulj yes you are right in case you want to write a project containing any custom code this would be helpful. till today nobody ever asked for it but I'll try to look into this soonish. THX for reporting this improvement suggestion!

**Comment by hpgrahsl** [comment]
Fixed with release 1.3.0 -> find it on maven central as of now. Enjoy!
