### ISSUE TITLE
The Renamer post processor does'nt call the next ones

### ISSUE THREAD

**Issue by zthulj** [hpgrahsl/kafka-connect-mongodb#76]
Hi,

I've seen that when we use the RenameByMapping that extends the Renamer PostProcessor, it won't call the following postProcessors (if they exist).

I think this is a bug.

As the fix seems easy, I can provide a PR.

### How to reproduce : 
- Create a sample post processor
- Use this line when creating the connector : "mongodb.post.processor.chain":"at.grahsl.kafka.connect.mongodb.processor.field.renaming.RenameByMapping,your.sample.TestPostProcessor"

### Expected Behaviour
The TestPostProcessor process method should be called after the process of RenameByMapping

### Actual Behaviour
The TestPostProcessor process isn't called

**Comment by hpgrahsl** [comment]
Many THX @zthulj for spotting and reporting this bug. It's correct that it has to call potential next post processors in order not to break the chain. I am going to fix this with the next patch release 1.3.1 which is planned to get done soonish.
