### ISSUE TITLE
Unable to connect to MongoDB using TLS

### ISSUE THREAD

**Issue by hazarika** [hpgrahsl/kafka-connect-mongodb#88]
I have a setup in which a golang  app is producing records to a Kafka cluster and kafka-connect-mongodb is acting as a the sink to a local MongoDB cluster.

The issue I am facing is I am unable to connect to MongodB once TLS is enabled.

MongoDB startup: 
`mongod -v --port 27017 --dbpath /var/lib/mongodb/ --replSet rs0 --auth  --sslMode requireSSL --sslPEMKeyFile /path/to/server.pem --sslCAFile /path/to/ca.pem`

Connector :

```
curl -X POST \
  http://localhost:8083/connectors \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: localhost:8083' \
  -H 'Postman-Token: efde734d-a14b-4604-9c9a-5d9694a83b34,6552f42b-f277-4c14-8377-5abaf0b68385' \
  -H 'User-Agent: PostmanRuntime/7.15.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 773' \
  -d '{
    "name": "mongo-sink",
    "config": {
        "connector.class": "com.mongodb.kafka.connect.MongoSinkConnector",
        "tasks.max": "1",
        "topics": "myTopic",
        "connection.uri": "mongodb://user:pass@127.0.0.1:27017/myDB?ssl=true&replicaSet=rs0",
        "database": "myDB",
        "collection": "collection1",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false",
    }
}
```

When kafka-connect-mongodb tries to write to MongoDB, I get the following error:

```
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
```
So, I imported the certificates to jre keystore (/usr/lib/jvm/java-8-oracle/jre/lib/security/cacerts) and I get the following error:

```
INFO Exception in monitor thread while connecting to server 127.0.0.1:27017 (org.mongodb.driver.cluster:76)
com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:112)
```

Next, I tried setting the keystore and truststore jks location path in connect-distributed.properties file and got the same error.

```
ssl.truststore.location=/path/to/truststore.jks
ssl.truststore.password=pass
ssl.keystore.type=JKS
ssl.keystore.location=/path/to/client.jks
ssl.keystore.password=pass
```

Finally as a sort of hack, I added the following options in KAFKA_JMX_OPTS in kafka-run-class.sh and I was able to successfully connect to Mongo DB

```
-Djavax.net.ssl.trustStore=/path/to/truststore.jks 
-Djavax.net.ssl.trustStorePassword=pass 
-Djavax.net.ssl.keyStore=/path/to/client.jks 
-Djavax.net.ssl.keyStorePassword=pass

```
Can you tell me where I am going wrong? Where do I set the JVM ssl properties?  Is setting it in KAFKA_JMX_OPTS the right approach?

**Comment by hazarika** [comment]
I figured out that we can export the KAFKA OPTS env variable. closing the issue.

**Comment by hpgrahsl** [comment]
@hazarika thx for your clarification on this. as always I'm happy to learn more about your use case - highly appreciated if you would be willing to share this :)
