### ISSUE TITLE
Mongo sink connector removing columns on MongoSink data change 

### ISSUE THREAD

**Issue by vaibhavpatil123** [hpgrahsl/kafka-connect-mongodb#89]
Config for Sink connector :

> {
> 
>       "connector.class": "at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector",
>         "transforms.mongoflatten.type": "io.debezium.connector.mongodb.transforms.UnwrapFromMongoDbEnvelope",
>         "tasks.max": "1",
>         "topics": "mongodb1.inventory.orders",
>         "mongodb.connection.uri": "mongodb://root:root@localhost:12122/ft-db?authSource=admin&authMechanism=SCRAM-SHA-1",
>         "database.history.kafka.bootstrap.servers": "kafka:9092",
>         "transforms": "mongoflatten",
>         "mongodb.collections": "orders",
>         "mongodb.delete.on.null.values": "true",
>         "auto.evolve": "true",
>         "name": "sink_mongodb_connector",
>         "auto.create": "true",
>         "mongodb.collection": "orders",
>         "mongodb.document.id.strategy": "at.grahsl.kafka.connect.mongodb.processor.id.strategy.FullKeyStrategy",
>       
>         "mongodb.databases": "ft-pune-paso_ne"
>     
> 	}

Config for source connector :

{
    "name": "src_mongo_connector1",
    "config": {
        "connector.class": "io.debezium.connector.mongodb.MongoDbConnector",
        "mongodb.password": "dbz",
        "tasks.max": "1",
        "mongodb.database": "inventory",
        "database.history.kafka.bootstrap.servers": "kafka:9092",
        "mongodb.user": "debezium",
        "name": "src_mongo_connector1",
        "mongodb.name": "mongodb1",
        "database.whitelist": "inventory",
        "mongodb.hosts": "rs0/10.236.1.108:27017",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter.schemas.enable": "true",
        "value.converter.schemas.enable": "true",
        "transforms.unwrap.type": "io.debezium.connector.mongodb.transforms.UnwrapFromMongoDbEnvelope"
    }
}

ISSUE :::::::

1 Mongodb target sink database documents attribute removes on update record 
2 Delete document not working as new ID inserted in target database.

Help needed to fix this issue.
Let me know if any inputs required.

**Comment by vaibhavpatil123** [comment]
Overall form **Src MongoDB >>>> We want to move data to Target MongoDB**
Using kafka connectors

**Comment by vaibhavpatil123** [comment]
Source Database record ::

**{ 
    "_id" : ObjectId("5d18a0d4084bd726535a7402"), 
    "order_date" : ISODate("2016-01-16T00:00:00.000+0000"), 
    "purchaser_id" : NumberLong(5555), 
    "quantity" : NumberInt(121212), 
    "product_id" : NumberLong(2323)
}**

If I update only **purchaser_id** filed then only purchaser_id is added in target sink database and other columns removing 👎 
{ 
    "_id" : ObjectId("5d18a115e6f308d2492080ab"), 
    "purchaser_id" : NumberLong(5555), 
    "id" : "5d18a0d4084bd726535a7402"
}

**Comment by vaibhavpatil123** [comment]
Sink database records should not drop document attributes

**Comment by hpgrahsl** [comment]
@vaibhavpatil123 hi there! thx for reaching out.

From what I've read above, you most likely want to get change-data-capture (CDC) behaviour from the source into the sink. In case I'm right please make use of a correct CDC configuration according to the documentation - README is your friend here :) 

1) no unwrap SMT needed
2) add cdc handler configuration
3) get rid of delete on null values (not needed when CDC mode is used)

doing so should hopefully fix your problems, both #89 + #90

**Comment by hpgrahsl** [comment]
closing this for now due to long inactivity period. reopen later if needed.
