### ISSUE TITLE
Cannot create field 'external_xmp_develop_setting' in element {1: null}

### ISSUE THREAD

**Issue by rajarameshyv** [hpgrahsl/kafka-connect-mongodb#96]
@hpgrahsl 
I am getting below exception from sink.

My sink propertirs:
name=oz_next_assets_sink_01
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

connector.class=at.grahsl.kafka.connect.mongodb.MongoDbSinkConnector
topics=oz_next_assets.oz_next.assets
mongodb.connection.uri=mongodb://localhost:27017/oz_next_new?w=1&journal=true
mongodb.change.data.capture.handler=at.grahsl.kafka.connect.mongodb.cdc.debezium.mongodb.MongoDbHandler
mongodb.collections=assets
mongodb.collection.oz_next_assets.oz_next.assets=assets

#Route failed messages to a dead letter queue
errors.tolerance=all
errors.deadletterqueue.topic.name=dlq_oz_new_assets_sink_01
#To include the reason for rejection in the header of the dead letter queue message
errors.deadletterqueue.context.headers.enable=true
#Recording the failure reason for a message: Log
errors.log.enable=true
errors.log.include.messages=true

Exception:
[2019-07-23 16:24:04,270] ERROR error on mongodb operation (at.grahsl.kafka.connect.mongodb.MongoDbSinkTask:160)
com.mongodb.MongoBulkWriteException: Bulk write operation error on server localhost:27017. Write errors: [BulkWriteError{index=263, code=28, message='Cannot create field 'external_xmp_develop_setting' in element {1: null}', details={}}].
        at com.mongodb.connection.BulkWriteBatchCombiner.getError(BulkWriteBatchCombiner.java:177)
        at com.mongodb.connection.BulkWriteBatchCombiner.throwOnError(BulkWriteBatchCombiner.java:206)
        at com.mongodb.connection.BulkWriteBatchCombiner.getResult(BulkWriteBatchCombiner.java:147)
        at com.mongodb.operation.BulkWriteBatch.getResult(BulkWriteBatch.java:227)
        at com.mongodb.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:280)
        at com.mongodb.operation.MixedBulkWriteOperation.access$700(MixedBulkWriteOperation.java:70)
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:203)
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:194)
        at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:424)
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:194)
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:69)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:193)
        at com.mongodb.client.internal.MongoCollectionImpl.executeBulkWrite(MongoCollectionImpl.java:468)
        at com.mongodb.client.internal.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:448)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.processSinkRecords(MongoDbSinkTask.java:148)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$null$0(MongoDbSinkTask.java:118)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.lambda$put$1(MongoDbSinkTask.java:117)
        at java.util.HashMap.forEach(HashMap.java:1289)
        at at.grahsl.kafka.connect.mongodb.MongoDbSinkTask.put(MongoDbSinkTask.java:112)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-07-23 16:24:04,270] ERROR writing 497 document(s) into collection [oz_next_new.assets] failed -> remaining retries (0) (at.grahsl.kafka.connect.mongodb.MongoDbSinkTask:161)

**Comment by hpgrahsl** [comment]
hi again @rajarameshyv 
were you already successful in reproducing this error in a different context i.e. outside of the mongodb connector e.g. just within the mongoshell or some leveraging some other drivers doing comparable insertions?

**Comment by hpgrahsl** [comment]
@rajarameshyv any news on this?

**Comment by rajarameshyv** [comment]
@hpgrahsl No fix found yet. I am getting the same error on different fields of the document. Examples below.  My current challenge is I am not able to find the actual source document that causing this issue. As I am new to Kafka, I am not able to dump full document to logfile along with error. Logfile contains only exception error but not the mongo document it is failing on. Appreciate, if you know how to get to problematic document, please share steps and weblink so that I can debug and try to fix the problem. 

BulkWriteError{index=157, code=28, message='Cannot create ` field 'proxies' ` in element {2: null}', details={}}
BulkWriteError{index=263, code=28, message='Cannot create field 'external_xmp_develop_setting' in element {1: null}', details={}}
BulkWriteError{index=24, code=28, message='Cannot create field 'master' in element {1: null}', details={}}
BulkWriteError{index=27, code=28, message='Cannot create field 'updated' in element {1: null}', details={}}
BulkWriteError{index=135, code=28, message='Cannot create field 'renditions' in element {2: null}', details={}}

**Comment by hpgrahsl** [comment]
@rajarameshyv I think it should help a lot already to run kafka connect with debug log level. then it shows you a lot more information in the logs, e.g. the full sink record. hopefully it becomes clear then what really causes this strange issue.

**Comment by rajarameshyv** [comment]
@hpgrahsl Your debug suggestion helped to find problem documents on the target where connector writing. This is what I found.

Somehow on target for some documents, I feel connector inserting 'null' value in some scenarios. Please see attached files. I am attaching an original document from source, document after the connector copied over to target and BulkWrite command with updates. If you wanted to reproduce problem I am facing, 
1. Insert document from file document_on_target.json.
2. Run bulkwrite command from testRun_on_kafkaconnectbreaker.json again document you inserted from step 1.
3. Compare documents from document_from_source.json & document_on_target.json.

[Archive.zip](https://github.com/hpgrahsl/kafka-connect-mongodb/files/3598075/Archive.zip)

**Comment by rajarameshyv** [comment]
@hpgrahsl And one more thing I notice is, before 'initsync' complete, I see connector trying to update documents may be from oplog. I am not sure this is expected behavior. My expectation is connector first completes all initsync step to target mongodb and then will start reading from oplog and runs INSERT, DELETE and UPDATE.

Why I am saying this? Please take a look at couple of lines from my DEBUG mode. It says initsync is **false**. Also, full log attached if you wanted to take a look. 

`source={sec=1566705991, ord=10, rs=oz_next_shard-2, connector=mongodb, ns=oz_next.assets, **initsync=false**, name=oz_next_assets, h=6230140048548470377, version=0.9.5.Final}`

Debug log:
DEBUG key: {"id": "\"345ca25d2b9a9b0e674b4f977db09cfe\""} (at.grahsl.kafka.connect.mongodb.cdc.debezium.mongodb.MongoDbHandler:72)
DEBUG value: {"patch": null, "op": "c", "after": "{\"_id\" : \"345ca25d2b9a9b0e674b4f977db09cfe\",\"storage\" : {\"size\" : 0,\"sha256\" : null,\"account_id\" : \"91a9308050b29c2035da32d7c60e7a4b\",\"updated\" : {\"$numberLong\" : \"1566705991486553\"},\"billed\" : true,\"revision\" : {\"_id\" : \"13be87ddeab76b8dc1c990cd1e456c83\",\"source\" : \"importSource.fileSize\"}},\"document_id\" : \"AWzG9D8+ChYGIy8Eldgw\",\"created\" : {\"$numberLong\" : \"1566705991486553\"},\"updated\" : {\"$numberLong\" : \"1566705991486553\"},\"catalog_id\" : \"dbb57af7ace73a5766b5c7697ac275fb\",\"payload\" : {\"captureDate\" : \"0000-00-00T00:00:00\",\"importSource\" : {\"fileName\" : \"uploaded_2019_08_25T04_06_31_486\",\"importTimestamp\" : \"2019-08-25T04:06:31.486Z\",\"importedBy\" : \"91a9308050b29c2035da32d7c60e7a4b\"}},\"latest_revision_id\" : \"13be87ddeab76b8dc1c990cd1e456c83\",\"latest_revision_created_by\" : \"91a9308050b29c2035da32d7c60e7a4b\",\"valid_revisions\" : [\"13be87ddeab76b8dc1c990cd1e456c83\"],\"valid_sha256_revisions\" : [\"13be87ddeab76b8dc1c990cd1e456c83\"],\"renditions\" : { },\"proxies\" : { },\"revisions\" : [{\"created\" : {\"$numberLong\" : \"1566705991486553\"},\"created_by\" : \"91a9308050b29c2035da32d7c60e7a4b\",\"updated\" : {\"$numberLong\" : \"1566705991486553\"},\"payload\" : {\"version\" : 1,\"captureDate\" : \"0000-00-00T00:00:00\"},\"renditions\" : { },\"proxies\" : { },\"id\" : \"13be87ddeab76b8dc1c990cd1e456c83\"}],\"revision_ids\" : [\"13be87ddeab76b8dc1c990cd1e456c83\"],\"storage_ver\" : 2,\"valid_external_xmp_cr_revisions\" : [],\"asset_model_version\" : 2,\"v1_payload\" : {\"importSource\" : {\"fileName\" : null,\"importedBy\" : null,\"importTimestamp\" : null}}}", "source": {"sec": {"$numberLong": "1566705991"}, "ord": {"$numberLong": "6"}, "rs": "oz_next_shard", "connector": "mongodb", "ns": "oz_next.assets", "initsync": false, "name": "oz_next_assets", "h": {"$numberLong": "-8967138018232918508"}, "version": "0.9.5.Final"}, "ts_ms": {"$numberLong": "1566705991487"}} (at.grahsl.kafka.connect.mongodb.cdc.debezium.mongodb.MongoDbHandler:73)
DEBUG SinkRecord{kafkaOffset=55104800, timestampType=CreateTime} ConnectRecord{topic='oz_next_assets.oz_next.assets', kafkaPartition=0, key={id="6aed272b51bdc52f9c8db9bd0b18ba43"}, keySchema=null, value={patch={"$set" : {"revisions.2.updated" : {"$numberLong" : "1566705991557463"},"revisions.2.renditions.thumbnail2x" : {"id" : "9e715955e668189cb7fd9afd9f7384e4","created_by" : "ea17e7363a58386267096688ec26cffa","created" : {"$numberLong" : "1566705991557463"},"created_by_ip" : "192.150.18.2, 10.76.212.88, 10.76.213.16"}}}, op=u, after=null, source={sec=1566705991, ord=10, rs=oz_next_shard-2, connector=mongodb, ns=oz_next.assets, initsync=false, name=oz_next_assets, h=6230140048548470377, version=0.9.5.Final}, ts_ms=1566705991557}, valueSchema=null, timestamp=1566705991906, headers=ConnectHeaders(headers=)} (at.grahsl.kafka.connect.mongodb.converter.SinkConverter:39)
DEBUG using schemaless converter (at.grahsl.kafka.connect.mongodb.converter.SinkConverter:67)
DEBUG using schemaless converter (at.grahsl.kafka.connect.mongodb.converter.SinkConverter:67)
DEBUG key: {"id": "\"6aed272b51bdc52f9c8db9bd0b18ba43\""} (at.grahsl.kafka.connect.mongodb.cdc.debezium.mongodb.MongoDbHandler:72)
DEBUG value: {"patch": "{\"$set\" : {\"revisions.2.updated\" : {\"$numberLong\" : \"1566705991557463\"},\"revisions.2.renditions.thumbnail2x\" : {\"id\" : \"9e715955e668189cb7fd9afd9f7384e4\",\"created_by\" : \"ea17e7363a58386267096688ec26cffa\",\"created\" : {\"$numberLong\" : \"1566705991557463\"},\"created_by_ip\" : \"192.150.18.2, 10.76.212.88, 10.76.213.16\"}}}", "op": "u", "after": null, "source": {"sec": {"$numberLong": "1566705991"}, "ord": {"$numberLong": "10"}, "rs": "oz_next_shard-2", "connector": "mongodb", "ns": "oz_next.assets", "initsync": false, "name": "oz_next_assets", "h": {"$numberLong": "6230140048548470377"}, "version": "0.9.5.Final"}, "ts_ms": {"$numberLong": "1566705991557"}} (at.grahsl.kafka.connect.mongodb.cdc.debezium.mongodb.MongoDbHandler:73)
DEBUG SinkRecord{kafkaOffset=55104801, timestampType=CreateTime} ConnectRecord{topic='oz_next_assets.oz_next.assets', kafkaPartition=0, key={id="6aed272b51bdc52f9c8db9bd0b18ba43"}, keySchema=null, value={patch={"$set" : {"updated" : {"$numberLong" : "1566705991557463"},"renditions.thumbnail2x" : {"revision_id" : "914ce6498d809f46ccc5e6dc87f4b7d4","id" : "9e715955e668189cb7fd9afd9f7384e4","created_by_ip" : "192.150.18.2, 10.76.212.88, 10.76.213.16"}}}, op=u, after=null, source={sec=1566705991, ord=11, rs=oz_next_shard-2, connector=mongodb, ns=oz_next.assets, initsync=false, name=oz_next_assets, h=-521186298104252537, version=0.9.5.Final}, ts_ms=1566705991561}, valueSchema=null, timestamp=1566705991906, headers=ConnectHeaders(headers=)} (at.grahsl.kafka.connect.mongodb.converter.SinkConverter:39)

[488docs_fail-2.log.zip](https://github.com/hpgrahsl/kafka-connect-mongodb/files/3598109/488docs_fail-2.log.zip)

**Comment by rajarameshyv** [comment]
@hpgrahsl Just checking if you were able to reproduce the error.

**Comment by hpgrahsl** [comment]
hi @rajarameshyv. unfortunately I didn't find the time to dive into this yet. drowing in work these days... but thx for providing all the detailed info about the issue including debug logs etc.

**Comment by rajarameshyv** [comment]
@hpgrahsl I recently tested Kafka-MongoDB connector version 1.0 and I don't see this issue anymore. I am curious how this is fixed. Appreciate if you can share fix that rolled into to address this issue if you can. Thank You.

**Comment by hpgrahsl** [comment]
@rajarameshyv thx for getting back to this. are you sure that the only thing that changed is the connector version and everything else in your pipeline is the same including the data itself? so:
1) the same mongodb source database version
2) holding the same data
3) the same Debezium MongoDB source connector version
4) same kafka topic settings + partition count
5) ONLY change: instead my community sink connector you use the official sink connetor? 
6) same mongodb sink database version

the reason I'm asking this is that I'm currently not aware of any sink connector related change in the official sink connector - I guess this is what you referred to above when writing version 1.0 - that would have changed write behaviour in this regard. in other words, I don't see why this should work now but didn't before. maybe we can find this out together. what's still puzzling me is that fact that I haven't seen the issue described above by any other users of which there are many by now.

**Comment by rajarameshyv** [comment]
@hpgrahsl you are right. I hit this issue now. Earlier I was testing with test data where I didn't see the issue with sink 1.0. But with production traffic, I am hitting the same java.lang.NullPointerException issue. I am not sure why? 

I am using source and sink DB versions as 3.6.8. 
And I saw one note on your git README saying "! IMPORTANT NOTE ! This WriteModelStrategy needs MongoDB version 4.2+ and Java Driver 3.11+ since lower versions of either lack the support for leveraging update pipeline syntax which is needed to perform the conditional checks during write operations.". Is that mean I need to be on 4.2+ for sink DB? Can you please clarify?
